stages:
  data_ingestion:
    cmd: python src/Classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Classifier/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion

  prepare_base_model:
    cmd: python src/Classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/Classifier/pipeline/stage_02_prepare_base_model.py
      - configs/config.yaml
      - params.yaml
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/Classifier/pipeline/stage_03_training.py
    deps:
      - src/Classifier/pipeline/stage_03_training.py
      - artifacts/prepare_base_model
      - artifacts/prepare_callbacks
      - artifacts/data_ingestion
      - configs/config.yaml
      - params.yaml
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/Classifier/pipeline/stage_04_model_evaluation.py 
    deps:
      - python src/Classifier/pipeline/stage_04_model_evaluation.py 
      - artifacts/valid_data
      - artifacts/training/model.h5
    metrics:
    - score.json:
        cache: false