artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
  local_data_file: artifacts/data_ingestion/zip_dir/data.zip
  unzip_dir: artifacts/data_ingestion/un_zip_dir
  eval_dir: artifacts/eval_data

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model/base_model.h5
  updated_model_path: artifacts/prepare_base_model/updated_model/updated_base_model.h5


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_log_dir: artifacts/prepare_callbacks/tensorboard_log
  checkpoint_model_path: artifacts/prepare_callbacks/checkpoint_model/model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

# validation:
#   root_dir: artifacts/validation
